name: test
on:
  pull_request_target:
    types: [labeled]
  push:

jobs:
  build:
    strategy:
      matrix:
        go-version: [^1]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    env:
      GO111MODULE: "on"
      UPYUN_BUCKET: ${{ secrets.UPYUN_BUCKET }}
      UPYUN_NOTIFY: ${{ secrets.UPYUN_NOTIFY }}
      UPYUN_PASSWORD: ${{ secrets.UPYUN_PASSWORD }}
      UPYUN_SECRET: ${{ secrets.UPYUN_SECRET }}
      UPYUN_USERNAME: ${{ secrets.UPYUN_USERNAME }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}

      - name: Download Go modules
        run: go mod download

      - name: Test
        run: |
          cd upyun && go test -v -p 1
